### ISSUE TITLE
paddle_detection can't use pretrain_weights in FedVision?

### ISSUE THREAD

**Issue by kevinsummer219** [FederatedAI/FedVision#28]

**Comment by kevinsummer219** [comment]
if use pretrain_weights, it will occus error. Thanks!
Traceback (most recent call last):
  File "/home/yangyu/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yangyu/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yangyu/work/fed_train/FedVision/fedvision/ml/paddle/paddle_detection/fl_trainer.py", line 234, in <module>
    fl_trainer()
  File "/home/yangyu/work/fed_train/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yangyu/work/fed_train/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yangyu/work/fed_train/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yangyu/work/fed_train/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yangyu/work/fed_train/FedVision/fedvision/ml/paddle/paddle_detection/fl_trainer.py", line 176, in fl_trainer
    checkpoint.load_params(
  File "/home/yangyu/work/fed_train/FedVision/ppdet/utils/checkpoint.py", line 152, in load_params
    fluid.io.set_program_state(prog, state)
  File "/home/yangyu/work/fed_train/venv/lib/python3.8/site-packages/paddle/fluid/io.py", line 1959, in set_program_state
    assert var_temp != None, \
AssertionError: Variable [ conv5_1_dw_bn_offset.opti.trainer_0 ] Not found, Please make sure run startup program
