### ISSUE TITLE
部署fedVision报错

### ISSUE THREAD

**Issue by houjibofa2050** [FederatedAI/FedVision#32]
使用的是fedvision-deploy deploy deploy --config standalone_template.yaml 命令
报错信息如下
Traceback (most recent call last):

  File "/root/fedvision/fedvision/bin/fedvision-deploy", line 8, in <module>
    sys.exit(app())

  File "/root/fedvision/fedvision/lib/python3.6/site-packages/fedvision_deploy_toolkit/_deploy.py", line 44, in deploy
    _maybe_create_python_venv(machine)

  File "/root/fedvision/fedvision/lib/python3.6/site-packages/fedvision_deploy_toolkit/_deploy.py", line 69, in _maybe_create_python_venv
    raise RuntimeError(f"python executable {machine['python']} not valid")

KeyError: 'python'

standalone_template.yaml 文件
`
machines:
  - name: machine1
    ip: 127.0.0.1
    ssh_string: 127.0.0.1:22
    base_dir: /data/projects/fedvision
    python_for_venv_create: python3 # use to create venv, python3.7+ required

# coordinator start/stop only if machine provided
coordinator:
  name: coordinator1
  machine: machine1
  port: 10000

clusters:
  - name: cluster1
    manager:
      machine: machine1
      port: 10001
    workers:
      - name: worker1
        machine: machine1
        ports: 12000-12099
        max_tasks: 10

masters:
  - name: master1
    machine: machine1
    submit_port: 10002
    coordinator: coordinator1
    cluster: cluster1

  - name: master2
    machine: machine1
    submit_port: 10003
    coordinator: coordinator1
    cluster: cluster1

  - name: master3
    machine: machine1
    submit_port: 10004
    coordinator: coordinator1
    cluster: cluster1

  - name: master4
    machine: machine1
    submit_port: 10005
    coordinator: coordinator1
    cluster: cluster1
`

**Comment by jaysontree** [comment]
他启动时是这样的，会ssh到每台机器上然后 验证python版本 -> 创建虚拟环境 -> 拷贝代码 -> 在虚拟环境安装依赖
你报这个错的原因是在验证python版本就错了。看看部署的机器上 python3 能否执行、版本符不符合要求。

报错的内容是配置里没'python'这个key，这个是作者代码的问题，正常的话不会走到这个分支。跟实际的问题没有关系、
